/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Window.java
 *
 * Created on 17.10.2013, 7:44:48
 */
package tetris;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author beh01
 */
public class Window extends javax.swing.JFrame {

    private Timer t;
    private Board board;
    private Block block;
    private JLabel labels[][] = new JLabel[20][10];

    /** Creates new form Window */
    public Window() {
        initComponents();

        t = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                tick();
            }
        });

        mainPanel.setLayout(new GridLayout(20, 10));

        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 10; j++) {
                labels[i][j] = new JLabel();
                labels[i][j].setBackground(Color.white);
                labels[i][j].setOpaque(true);
                mainPanel.add(labels[i][j]);
            }
        }
    }

    void newPrint() {
        for (int i = 0; i < board.getNumberOfRows(); i++) {
            for (int j = 0; j < board.getNumberOfColumns(); j++) {
                if (board.getCell(i, j)) {
                    labels[i][j].setBackground(Color.red);
                } else {
                    labels[i][j].setBackground(Color.black);
                }
            }
        }
        int cells[][] = block.getCellsCoordinates();
        for (int i = 0; i < 4; i++) {
            labels[cells[i][0]][cells[i][1]].setBackground(Color.blue);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newButton = new javax.swing.JButton();
        endGame = new javax.swing.JButton();
        keyPresed = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        newButton.setText("New game");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        endGame.setText("Stop");
        endGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endGameActionPerformed(evt);
            }
        });

        keyPresed.setText("jLabel1");

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(keyPresed)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(endGame, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endGame)
                        .addGap(76, 76, 76)
                        .addComponent(keyPresed)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        board = new Board();
        //just to test...
       // board.setCell(5, 5, true);

        this.requestFocus();

        block = genNewBlock();
        newPrint();
        t.start();

    }//GEN-LAST:event_newButtonActionPerformed

    private Block genNewBlock() {
        Random r = new Random();
        r.nextInt(6);
        //todo
        return new Block(board, BlockType.Line, 0, 4);
    }

    private void endGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endGameActionPerformed
        t.stop();
    }//GEN-LAST:event_endGameActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        keyPresed.setText("" + evt.getKeyCode());
        if (evt.getKeyCode() == 37) {
            block.moveLeft();
        }
        if (evt.getKeyCode() == 38) {
            block.rotate();
        }
        if (evt.getKeyCode() == 39) {
            block.moveRight();
        }
        newPrint();
    }//GEN-LAST:event_formKeyPressed
    private void tick() {
        boolean result = block.moveDown();
        if (result == false) {
            // kontrola, generuj novou kosticku
        }
        newPrint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endGame;
    private javax.swing.JLabel keyPresed;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
